import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import '@/styles/globals.css';
import { Navbar } from '@/components/Navbar/Navbar';

export const metadata: Metadata = {
  title: 'SaintHR',
  description: 'Generated by create next app',
};

const plusJakartaSans = Plus_Jakarta_Sans({
    variable: '--font-plus-jakarta-sans',
    subsets: ['latin'],
  });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en">
      <body className={`${plusJakartaSans.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
